services:
  postgres:
    image: postgres
    container_name: habr_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root_pass
      # появится бд root кроме postgres но можно задать POSTGRES_DB: postgres
    volumes:
      - ./deploy/postgres/init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
